BUCKET_PATTERN="claritytts-{env}-application-logs"
BUCKET_PROD="claritytts-prod-application-logs"
VALID_ENVS="dev qa uat prod"
OUTPUT_ENGINE="$HOME/Downloads/logs/engine"
OUTPUT_API="$HOME/Downloads/logs/api"
DEFAULT_PROFILE=""
ENGINE_SEARCH_PREFIX="engine-search-logs"
ENGINE_BOOKING_PREFIX="engine-booking-logs"
B2B2C_PREFIX="b2b2c-logs"
